title: Albert ________.
description: "Albert Cornelissen: Tinkers, takes pictures, writes occasionally."
baseurl: ""
url: "https://cornelissen.me"
markdown: kramdown

plugins:
  - jekyll-sitemap

exclude:
  - bin
  - Gemfile
  - Gemfile.lock
  - README.md

defaults:
  - scope:
      path: "ph"
    values:
      layout: gallery
      title: Albert takes pictures.
  - scope:
      path: "writing"
    values:
      layout: post
      title: Albert writes.
